#!/bin/sh
curl -s -L -O http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.3.1/binaries/apache-maven-3.3.1-bin.zip
curl -s -L -O http://download.java.net/glassfish/4.1/release/glassfish-4.1.zip
